### ISSUE TITLE
can't update add-on to 2.0.2 on linux

### ISSUE THREAD

**Issue by mepreston** [getflywheel/local-addon-backups#92]
attempting to update the add-on to 2.0.2 hangs on linux with these errors:

{"thread":"main","class":"Updater","level":"info","message":"Checking for updates for: linux-x64-production","timestamp":"2023-04-13T18:20:29.372Z"}
{"thread":"main","class":"Updater","release":null,"level":"debug","message":"Check for updates result","timestamp":"2023-04-13T18:20:29.905Z"}
{"thread":"renderer","class":"RendererAddonLoader","level":"debug","message":"Loading Add-on: %%userDataPath%%/addons/local-addon-backups/lib/renderer.js","timestamp":"2023-04-13T18:20:30.147Z"}
{"thread":"renderer","class":"RendererAddonLoader","level":"debug","message":"Successfully Loaded Add-on: %%userDataPath%%/addons/local-addon-backups/lib/renderer.js","timestamp":"2023-04-13T18:20:30.310Z"}
{"thread":"main","class":"AddonInstallerService","level":"info","message":"Updating Add-on '@getflywheel/local-addon-backups' release '[object Object]'","timestamp":"2023-04-13T18:20:40.616Z"}
{"thread":"main","class":"AddonInstallerService","level":"info","message":"Removing existing Add-on to finish update","timestamp":"2023-04-13T18:20:50.465Z"}
{"thread":"main","reason":{"errno":-18,"syscall":"rename","code":"EXDEV","path":"/tmp/local-nTzYjYfcG/package","dest":"%%userDataPath%%/addons/@getflywheel-local-addon-backups"},"p":{},"eventId":"13c94895d7ae471bbb737be7b2abd57f","level":"warn","message":"Unhandled Rejection.","timestamp":"2023-04-13T18:20:50.468Z"}
{"thread":"main","name":"UnhandledPromiseRejectionWarning","level":"info","message":"Warning:Error: EXDEV: cross-device link not permitted, rename '/tmp/local-nTzYjYfcG/package' -> '%%userDataPath%%/addons/@getflywheel-local-addon-backups'\n    at Object.renameSync (node:fs:993:3)\n    at Object.moveSync [as sync] (%%appPath%%/node_modules/fs-jetpack/lib/move.js:27:8)\n    at Object.move (%%appPath%%/node_modules/fs-jetpack/lib/jetpack.js:179:12)\n    at AddonInstallerService.<anonymous> (%%appPath%%/main/addons/AddonInstallerService.js:1:8055)\n    at Generator.next (<anonymous>)\n    at r (%%appPath%%/main/addons/AddonInstallerService.js:1:742)","stack":"UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/tmp/local-nTzYjYfcG/package' -> '%%userDataPath%%/addons/@getflywheel-local-addon-backups'\n    at Object.renameSync (node:fs:993:3)\n    at Object.moveSync [as sync] (%%appPath%%/node_modules/fs-jetpack/lib/move.js:27:8)\n    at Object.move (%%appPath%%/node_modules/fs-jetpack/lib/jetpack.js:179:12)\n    at AddonInstallerService.<anonymous> (%%appPath%%/main/addons/AddonInstallerService.js:1:8055)\n    at Generator.next (<anonymous>)\n    at r (%%appPath%%/main/addons/AddonInstallerService.js:1:742)\n    at emitUnhandledRejectionWarning (node:internal/process/promises:191:15)\n    at processPromiseRejections (node:internal/process/promises:270:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:97:32)","timestamp":"2023-04-13T18:20:50.469Z"}
{"thread":"main","level":"info","message":"Warning:Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)","stack":"Error: EXDEV: cross-device link not permitted, rename '/tmp/local-nTzYjYfcG/package' -> '%%userDataPath%%/addons/@getflywheel-local-addon-backups'\n    at Object.renameSync (node:fs:993:3)\n    at Object.moveSync [as sync] (%%appPath%%/node_modules/fs-jetpack/lib/move.js:27:8)\n    at Object.move (%%appPath%%/node_modules/fs-jetpack/lib/jetpack.js:179:12)\n    at AddonInstallerService.<anonymous> (%%appPath%%/main/addons/AddonInstallerService.js:1:8055)\n    at Generator.next (<anonymous>)\n    at r (%%appPath%%/main/addons/AddonInstallerService.js:1:742)","timestamp":"2023-04-13T18:20:50.469Z"}

i'm running on Fedora 37

**Comment by mepreston** [comment]
i'm running fedora 38
